routes/web.php
<?php

use App\Providers\AuthServiceProvider;

Auth::routes(['verify' => true]);
Route::get('/', function () {
    return redirect('admin');
});
Route::get('/home', 'HomeController@index')->middleware('verified');

// OAuth
//Route::get('callback', 'Oauth2Controller@callback');
//Route::get('/', function () {
//    $queryParams = [
//        'client_id' => '3',
//        'redirect_uri' => url('callback'),
//        'response_type' => 'code',
//        'scope' => '',
//    ];
//    return redirect(route('passport.authorizations.authorize', $queryParams));
//});
//Route::get('/create-role', function () {
//    $user = \App\Models\User::first();
//    $user->attachRole('admin');
//    dd($user);
//});

// Admin dashboard
Route::get('/admin', function () {
    return view('auth.login');
});

Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'middleware' => ['role:' . AuthServiceProvider::ROLE_ADMINISTRATOR], 'namespace' => 'Admin'], function () {
    Route::resource('users', 'UsersController');
    Route::resource('permission', 'PermissionController');
    Route::resource('roles', 'RolesController');
});
Route::group(['prefix' => 'admin', 'middleware' => 'auth', 'middleware' => ['role:' . AuthServiceProvider::ROLE_CLIENT_APP], 'namespace' => 'Admin'], function () {
    Route::get('oauth-dashboard', 'Oauth2Controller@index')->name('oauth-dashboard');
});

app/Http/Controllers/Admin/UsersController.php
<?php
namespace App\Http\Controllers\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\User;
use App\Models\RolePermissions\Role;
use App\Models\RolePermissions\Permission;

class UsersController extends Controller
{
    //
    public function __construct()
    {
        //$this->middleware('role:users');
    }
    // Index Page for Users
    public function index()
    {
        $users = User::paginate(10);

        $params = [
            'title' => 'Users Listing',
            'users' => $users,
        ];
        return view('admin.users.users_list')->with($params);
    }
    // Create User Page
    public function create()
    {
        $roles = Role::all();
        $params = [
            'title' => 'Create User',
            'roles' => $roles,
        ];
        return view('admin.users.users_create')->with($params);
    }
    // Store New User
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|unique:users',
            'password' => 'required',
        ]);
        $user = User::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => bcrypt($request->input('password')),
        ]);
        $role = Role::find($request->input('role_id'));
        $user->attachRole($role);
        return redirect()->route('users.index')->with('success', "The user <strong>$user->name</strong> has successfully been created.");
    }
    // Delete Confirmation Page
    public function show($id)
    {
        try {
            $user = User::findOrFail($id);
            $params = [
                'title' => 'Confirm Delete Record',
                'user' => $user,
            ];
            return view('admin.users.users_delete')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }
    // Editing User Information Page
    public function edit($id)
    {
        try {
            $user = User::findOrFail($id);
            //$roles = Role::all();
            $roles = Role::with('permissions')->get();
            $permissions = Permission::all();
            $params = [
                'title' => 'Edit User',
                'user' => $user,
                'roles' => $roles,
                'permissions' => $permissions,
            ];
            return view('admin.users.users_edit')->with($params);
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }
    // Update User Information to DB
    public function update(Request $request, $id)
    {
        try {
            $user = User::findOrFail($id);
            $this->validate($request, [
                'name' => 'required',
                'email' => 'required|email|unique:users,email,' . $id,
            ]);
            $user->name = $request->input('name');
            $user->email = $request->input('email');
            $user->save();
            // Update role of the user
            $roles = $user->roles;
            foreach ($roles as $key => $value) {
                $user->detachRole($value);
            }
            $role = Role::find($request->input('role_id'));
            $user->attachRole($role);
            // Update permission of the user
            //$permission = Permission::find($request->input('permission_id'));
            //$user->attachPermission($permission);
            return redirect()->route('users.index')->with('success', "The user <strong>$user->name</strong> has successfully been updated.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }
    // Remove User from DB with detaching Role
    public function destroy($id)
    {
        try {
            $user = User::findOrFail($id);
            // Detach from Role
            $roles = $user->roles;
            foreach ($roles as $key => $value) {
                $user->detachRole($value);
            }
            $user->delete();
            return redirect()->route('users.index')->with('success', "The user <strong>$user->name</strong> has successfully been archived.");
        } catch (ModelNotFoundException $ex) {
            if ($ex instanceof ModelNotFoundException) {
                return response()->view('errors.' . '404');
            }
        }
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use App\Database\Eloquent\UserQueryBuilder;
use App\Http\Requests\StoreUser;
use App\Http\Requests\StoreStandardUserDataObject;
use App\Http\Requests\StoreApplicationUserDataObject;
use App\Http\Requests\UpdateApplicationUserDataObject;
use App\Http\Requests\UpdateStandardUserDataObject;
use App\Http\Requests\UpdateUser;
use App\Http\Resources\UserFull as UserFullResource;
use App\Http\Resources\UserCollection;
use App\Models\User;
use App\Models\UserData;
use App\Providers\AuthServiceProvider;
use App\Traits\SavesUserData;
use Illuminate\Auth\Events\Registered;
use Illuminate\Support\Facades\Log;
use Laratrust\Laratrust;
use Lcobucci\JWT\Parser;

/**
 * Class UserController.
 */
class UserController extends Controller
{

    use SavesUserData;

    /**
     * Display a listing of the resource.
     *
     * @OA\Get(
     *     path="/users",
     *     summary="The list of users",
     *     tags={"user"},
     *     description="Get the list of users",
     *     operationId="listUsers",
     *     @OA\Response(
     *         response=200, description="successful operation",
     *         @OA\JsonContent(
     *             type="array",
     *             @OA\Items(ref="#/components/schemas/ExistingUser")
     *         ),
     *     ),
     *     @OA\Parameter(ref="#/components/parameters/user_includes"),
     *     @OA\Parameter(ref="#/components/parameters/user_sorts"),
     *     @OA\Parameter(ref="#/components/parameters/user_fields"),
     *     @OA\Parameter(ref="#/components/parameters/user_filters"),
     *     @OA\Parameter(ref="#/components/parameters/page"),
     *     @OA\Response(response=401, ref="#/components/responses/401"),
     *     @OA\Response(response=403, ref="#/components/responses/403"),
     *     @OA\Response(response=405, ref="#/components/responses/405"),
     *     @OA\Response(response=410, ref="#/components/responses/410"),
     *     @OA\Response(response=429, ref="#/components/responses/429"),
     *     security={{"passport": {L5_SAGGER_READ_USERS}}}
     * )
     *
     * @param UserQueryBuilder $queryBuilder
     * @return UserCollection
     */
    public function index(UserQueryBuilder $queryBuilder)
    {
        return new UserCollection($queryBuilder->paginate());
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
    }


    /**
     * Store a newly created resource in storage.
     *
     * @OA\Post(
     *     path="/users",
     *     tags={"user"},
     *     summary="Add a new user to the application",
     *     operationId="storeUser",
     *     @OA\Response(
     *         response=201, description="user created",
     *         @OA\JsonContent(ref="#/components/schemas/User")
     *     ),
     *     @OA\Response(response=422, ref="#/components/responses/422"),
     *     @OA\Response(response=401, ref="#/components/responses/401"),
     *     @OA\Response(response=403, ref="#/components/responses/403"),
     *     @OA\Response(response=405, ref="#/components/responses/405"),
     *     @OA\Response(response=410, ref="#/components/responses/410"),
     *     @OA\Response(response=429, ref="#/components/responses/429"),
     *     @OA\RequestBody(ref="#/components/requestBodies/User"),
     *     security={{"passport": {L5_SAGGER_MANAGE_USERS}}}
     * )
     *
     * @param StoreUser $request
     * @param StoreStandardUserDataObject $standardRequest
     * @param StoreApplicationUserDataObject $applicationRequest
     * @param Laratrust $laratrust
     * @return \Illuminate\Http\Response
     */
    public function store(StoreUser $request, StoreStandardUserDataObject $standardRequest,
                          StoreApplicationUserDataObject $applicationRequest, Laratrust $laratrust)
    {
        $this->hasRole(AuthServiceProvider::ROLE_ADMINISTRATOR, $laratrust);

        $clientId = (new Parser())->parse($request->bearerToken())->getClaim('aud');
        $user = $this->saveUser($request->validated(), $standardRequest->validated(), $applicationRequest->validated(), (int)$clientId);

        event(new Registered($user));

        return response(new UserFullResource($user), 201)
            ->header('Location', route('users.show', $user->id));
    }


    /**
     * Display the specified resource.
     *
     * @OA\Get(
     *     path="/current-user",
     *     summary="Get data of a current logged in user",
     *     tags={"user"},
     *     description="Returns the current logged in user",
     *     operationId="currentUser",
     *     @OA\Response(
     *         response=200, description="successful operation",
     *         @OA\JsonContent(ref="#/components/schemas/ExistingUser")
     *     ),
     *     @OA\Response(response=404, ref="#/components/responses/404"),
     *     @OA\Response(response=401, ref="#/components/responses/401"),
     *     @OA\Response(response=403, ref="#/components/responses/403"),
     *     @OA\Response(response=405, ref="#/components/responses/405"),
     *     @OA\Response(response=410, ref="#/components/responses/410"),
     *     @OA\Response(response=429, ref="#/components/responses/429"),
     *     security={{"passport": {L5_SAGGER_READ_USERS}}}
     * )
     *
     * @return UserFullResource
     */
    public function current()
    {
        $user = auth()->user();
        $userFullResource = new UserFullResource($user);
        $userFullResource['roles'] = $user->roles;
        return $userFullResource;
    }

    /**
     * Display the specified resource.
     *
     * @OA\Get(
     *     path="/users/{id}",
     *     summary="Find user by id",
     *     tags={"user"},
     *     description="Returns a singe user",
     *     operationId="showUser",
     *     @OA\Parameter(ref="#/components/parameters/id_in_path_required"),
     *     @OA\Response(
     *         response=200, description="successful operation",
     *         @OA\JsonContent(ref="#/components/schemas/ExistingUser")
     *     ),
     *     @OA\Response(response=404, ref="#/components/responses/404"),
     *     @OA\Response(response=401, ref="#/components/responses/401"),
     *     @OA\Response(response=403, ref="#/components/responses/403"),
     *     @OA\Response(response=405, ref="#/components/responses/405"),
     *     @OA\Response(response=410, ref="#/components/responses/410"),
     *     @OA\Response(response=429, ref="#/components/responses/429"),
     *     security={{"passport": {L5_SAGGER_READ_USERS}}}
     * )
     *
     * @param \App\Models\User $user
     *
     * @return UserFullResource
     */
    public function show(User $user)
    {
        return new UserFullResource($user);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param \App\Models\User $user
     *
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
    }


    /**
     * Update the specified resource in storage.
     *
     * @OA\Put(
     *     path="/users/{id}",
     *     tags={"user"},
     *     summary="Updatge an existing user",
     *     operationId="updateUser",
     *     @OA\Parameter(ref="#/components/parameters/id_in_path_required"),
     *     @OA\Response(
     *         response=200, description="user updated",
     *         @OA\JsonContent(ref="#/components/schemas/ExistingUser")
     *     ),
     *     @OA\Response(response=404, ref="#/components/responses/404"),
     *     @OA\Response(response=422, ref="#/components/responses/422"),
     *     @OA\Response(response=401, ref="#/components/responses/401"),
     *     @OA\Response(response=403, ref="#/components/responses/403"),
     *     @OA\Response(response=405, ref="#/components/responses/405"),
     *     @OA\Response(response=410, ref="#/components/responses/410"),
     *     @OA\Response(response=429, ref="#/components/responses/429"),
     *     @OA\RequestBody(ref="#/components/requestBodies/User"),
     *     security={{"passport": {L5_SAGGER_MANAGE_USERS}}}
     * )
     *
     * @param UpdateUser $request
     * @param User       $user
     * @param Laratrust $laratrust
     *
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUser $request, UpdateStandardUserDataObject $standardRequest,
                           UpdateApplicationUserDataObject $applicationRequest, User $user, Laratrust $laratrust)
    {
//        return response(['message' => $standardRequest->validated()]);

        $this->ownsOrHasRole(AuthServiceProvider::ROLE_ADMINISTRATOR, $user, $laratrust, 'id');

        $clientId = (new Parser())->parse($request->bearerToken())->getClaim('aud');
        $this->saveUser($request->validated(), $standardRequest->validated(), $applicationRequest->validated(), (int)$clientId, $user);

        return response(new UserFullResource($user));
    }


    /**
     * Remove the specified resource from storage.
     *
     * @OA\Delete(
     *     path="/users/{id}",
     *     summary="Deletes a user",
     *     tags={"user"},
     *     description="Deletes a singe user",
     *     operationId="deleteUser",
     *     @OA\Parameter(ref="#/components/parameters/id_in_path_required"),
     *     @OA\Response(response=204, ref="#/components/responses/204"),
     *     @OA\Response(response=404, ref="#/components/responses/404"),
     *     @OA\Response(response=401, ref="#/components/responses/401"),
     *     @OA\Response(response=403, ref="#/components/responses/403"),
     *     @OA\Response(response=405, ref="#/components/responses/405"),
     *     @OA\Response(response=410, ref="#/components/responses/410"),
     *     @OA\Response(response=429, ref="#/components/responses/429"),
     *     security={{"passport": {L5_SAGGER_MANAGE_USERS}}}
     * )
     *
     * @param \App\Models\User $user
     * @param Laratrust $laratrust
     *
     * @return \Illuminate\Http\Response
     * @throws \Exception

resources/views/admin/users/users_create.blade.php
@extends('layouts.adminpages') @section('content')

<main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Users</h1>
    </div>
    <a class="btn btn-sm btn-primary" href="{{route('users.index')}}">Back</a>
    <h2>{{$title}}</h2>
    <form method="post" action="{{ route('users.store') }}" data-parsley-validate class="form-horizontal form-label-left">

        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} row">
            <label for="name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type="text" value="{{ Request::old('name') ?: '' }}" id="name" name="name" class="form-control col-md-7 col-xs-12"> @if ($errors->has('name'))
                <span class="help-block">{{ $errors->first('name') }}</span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }} row">
            <label for="email" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input type="text" value="{{ Request::old('email') ?: '' }}" id="email" name="email" class="form-control col-md-7 col-xs-12"> @if ($errors->has('email'))
                <span class="help-block">{{ $errors->first('email') }}</span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }} row">
            <label for="password" class="col-sm-2 col-form-label">Password</label>
            <div class="col-sm-10">
                <input type="password" value="{{ Request::old('password') ?: '' }}" id="password" name="password" class="form-control col-md-7 col-xs-12"> @if ($errors->has('password'))
                <span class="help-block">{{ $errors->first('password') }}</span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('confirm_password') ? ' has-error' : '' }} row">
            <label for="confirm_password" class="col-sm-2 col-form-label">Confirm Password</label>
            <div class="col-sm-10">
                <input type="password" value="{{ Request::old('confirm_password') ?: '' }}" id="confirm_password" name="confirm_password"
                    class="form-control col-md-7 col-xs-12"> @if ($errors->has('confirm_password'))
                <span class="help-block">{{ $errors->first('confirm_password') }}</span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('role_id') ? ' has-error' : '' }} row">
            <label class="col-sm-2 col-form-label" for="category_id">Role
                <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <select class="form-control" id="role_id" name="role_id">
                    @if(count($roles)) @foreach($roles as $row)
                    <option value="{{$row->id}}">{{$row->name}}</option>
                    @endforeach @endif
                </select>
                @if ($errors->has('role_id'))
                <span class="help-block">{{ $errors->first('role_id') }}</span>
                @endif
            </div>
        </div>

        <div class="ln_solid"></div>

        <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <input type="hidden" name="_token" value="{{ Session::token() }}">
                <button type="submit" class="btn btn-success">Create User</button>
            </div>
        </div>
    </form>
</main>
</div>
</div>

@endsection

resources/views/admin/users/users_delete.blade.php
@extends('layouts.adminpages')

@section('content')

    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Users</h1>
    </div>
    <a class="btn btn-sm btn-primary" href="{{route('users.index')}}">Back</a>
    <h2>{{$title}}</h2>
    <div class="clearfix"></div>
    <p>Are you sure you want to delete <strong>{{$user->name}}</strong></p>

                    <form method="POST" action="{{ route('users.destroy', ['id' => $user->id]) }}">
                        <input type="hidden" name="_token" value="{{ Session::token() }}">
                        <input name="_method" type="hidden" value="DELETE">
                        <button type="submit" class="btn btn-danger">Yes I'm sure. Delete</button>
                    </form>
</main>
</div>
</div>
@endsection

resources/views/admin/users/users_edit.blade.php
@extends('layouts.adminpages')

@section('content')
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">

    <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Users</h1>
    </div>
    <a class="btn btn-sm btn-primary" href="{{route('users.index')}}">Back</a>
    <h2>{{$title}}</h2>
    <form method="post" action="{{ route('users.update', ['id' => $user->id]) }}" data-parsley-validate class="form-horizontal form-label-left">

        <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }} row">
            <label for="name" class="col-sm-2 col-form-label">Name</label>
            <div class="col-sm-10">
                <input type="text" value="{{$user->name}}" id="name" name="name" class="form-control col-md-7 col-xs-12"> @if ($errors->has('name'))
                <span class="help-block">{{ $errors->first('name') }}</span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }} row">
            <label for="email" class="col-sm-2 col-form-label">Email</label>
            <div class="col-sm-10">
                <input type="text" value="{{$user->email}}" id="email" name="email" class="form-control col-md-7 col-xs-12"> @if ($errors->has('email'))
                <span class="help-block">{{ $errors->first('email') }}</span>
                @endif
            </div>
        </div>

        <div class="form-group{{ $errors->has('role_id') ? ' has-error' : '' }} row">
            <label class="col-sm-2 col-form-label" for="category_id">Role
                <span class="required">*</span>
            </label>
            <div class="col-md-6 col-sm-6 col-xs-12">
                <select class="form-control" id="role_id" name="role_id">
                    @if(count($roles))
                    @foreach($roles as $row)
                    <option value="{{$row->id}}" {{$row->id == $user->roles[0]->id ? 'selected="selected"' : ''}}>{{$row->name}}</option>
                    @endforeach
                    @endif
                </select>
                @if ($errors->has('role_id'))
                <span class="help-block">{{ $errors->first('role_id') }}</span>
                @endif
            </div>
        </div>

        <div class="ln_solid"></div>

        <div class="form-group">
            <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                <input type="hidden" name="_token" value="{{ Session::token() }}">
                <input name="_method" type="hidden" value="PUT">
                <button type="submit" class="btn btn-success">Save User Changes</button>
            </div>
        </div>
    </form>
</main>
</div>
</div>
@endsection

resources/views/admin/users/users_list.blade.php
@extends('layouts.adminpages')

@section('content')
   
    <main role="main" class="col-md-9 ml-sm-auto col-lg-10 pt-3 px-4">
      
      <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pb-2 mb-3 border-bottom">
        <h1 class="h2">Users</h1>
      </div>
      <a class="btn btn-sm btn-primary" href="{{route('users.create')}}">Add New User</a>
      <h2>{{$title}}</h2>
      <div class="table-responsive">
        <table class="table table-striped table-sm">
          <thead>
            <tr>
              <th>Username</th>
              <th>Email</th>
              <th>Role</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody>
              @foreach($users as $user)
                  <tr>
                    <td>{{ $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>
                    @foreach($user->roles as $r)
                        {{$r->display_name}}
                    @endforeach
                    </td>
                    <td>
                      <div class="btn-group">
                        <a class="btn btn-primary" href="{{ route('users.edit', ['id' => $user->id]) }}" class="btn btn-info btn-xs"><i class="fa fa-pencil" title="Role"></i> </a>
                        <a class="btn btn-danger" href="{{ route('users.show', ['id' => $user->id]) }}" class="btn btn-danger btn-xs"><i class="fa fa-trash-o" title="Delete"></i> </a>
                      </div>
                    </td>
                  </tr>
                  @endforeach
          </tbody>
        </table>
        {{ $users->links() }}
      </div>
    </main>
  </div>
</div>
@endsection